site_name: HSKY WRLD
site_description: Knowledge Database of HSKY
repo_name: HuskyFTW
nav:
  - Home: index.md
  - Courses & Certificates:
    - TryHackMe: 
      - Jr Penetration Tester: 
        - Nmap: Courses/Jr Penetration Tester/Network Security/nmap.md
  - Utility:
    - Python: Python/python.md
    - Github:
      - Github Push: Github/Github push.md
theme:
  name: material
  logo: logo.png
  extra_css:
  - stylesheets/extra.css
  feature:
    masks:
      cover: false

  palette:
    # Light mode
    - media: '(prefers-color-scheme: light)'
      scheme: default
      primary: 'teal'
      accent: 'amber'
      toggle:
        icon: material/toggle-switch-off-outline
        name: Switch to dark mode

    # Dark mode
    - media: '(prefers-color-scheme: dark)'
      scheme: slate
      primary: 'amber'
      accent: 'amber'
      toggle:
        icon: material/toggle-switch
        name: Switch to light mode

    

