site_name: HSKY WRLD
site_description: Knowledge Database of HSKY
repo_name: HuskyFTW
nav:
  - Getting Started: index.md
  - Install: install.md
  - Full Example: example.md
theme:
   name: 'material'